services:

  postgres:
    env_file:
      - ./.env.production
    environment:
      POSTGRES_DB: ${DRUPAL_DB_NAME}
      POSTGRES_USER: ${DRUPAL_DB_USER}
      POSTGRES_PASSWORD: ${DRUPAL_DB_PASS}  
    
  drupal:
    env_file:
      - ./.env.production
    environment:
      DRUPAL_DB_HOST: ${DRUPAL_DB_HOST}
      DRUPAL_DB_NAME: ${DRUPAL_DB_NAME}
      DRUPAL_DB_USER: ${DRUPAL_DB_USER}
      DRUPAL_DB_PASS: ${DRUPAL_DB_PASS}
      DRUPAL_ADMIN_USER: ${DRUPAL_ADMIN_USER}
      DRUPAL_ADMIN_PASS: ${DRUPAL_ADMIN_PASS}
      DRUPAL_ADMIN_MAIL: ${DRUPAL_ADMIN_MAIL}
      DRUPAL_TRUSTED_HOSTS: ${DRUPAL_TRUSTED_HOSTS}
      DRUPAL_REVERSE_PROXY: ${DRUPAL_REVERSE_PROXY}
      DRUPAL_REVERSE_PROXY_ADDRESSES: ${DRUPAL_REVERSE_PROXY_ADDRESSES}
      DRUPAL_REVERSE_PROXY_TRUSTED_HEADERS: ${DRUPAL_REVERSE_PROXY_TRUSTED_HEADERS}
      DRUPAL_BASE_URL: ${DRUPAL_BASE_URL}
      DRUPAL_SITE_NAME: ${DRUPAL_SITE_NAME}
      CONFIG_SYNC_DIRECTORY: ${CONFIG_SYNC_DIRECTORY}
      DRUPAL_AUTO_IMPORT_ON_START: ${DRUPAL_AUTO_IMPORT_ON_START}
      DRUPAL_INSTALL_PROFILE: ${DRUPAL_INSTALL_PROFILE}
      DRUPAL_HASH_SALT: ${DRUPAL_HASH_SALT}
    command: ["/bin/bash", "/opt/drupal/start-drupal.sh"]
    restart: unless-stopped
    # Persistente Verzeichnisse auf dem Server (anpassen!):
    volumes:
      # Config & private auf Serverpfad mounten (bind mounts):
      - /srv/jfcamp/drupal/config:/opt/drupal/config
      - /srv/jfcamp/drupal/private:/opt/drupal/private
      # Optional: öffentliche Files, wenn genutzt (ansonsten bleiben in Container/Volume)
      # - /srv/jfcamp/drupal/files:/opt/drupal/web/sites/default/files
    depends_on:
      postgres:
        condition: service_healthy

  matching:
    env_file:
      - ./.env.production
    restart: unless-stopped
    depends_on:
      - drupal

  # Für PROD-Web-Frontend (statisches Build via Nginx); Basis-compose enthält bereits "vue-prod"
  vue-prod:
    # Aktiv in PROD (deine Basis-compose setzt profiles: [prod])
    restart: unless-stopped

# Keine zusätzlichen Volumes nötig – benannte Volumes aus Basis-compose bleiben bestehen.
