services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: drupal
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
    volumes:
      - db_data:/var/lib/postgresql/data

  drupal:
    build:
      context: ./drupal
      dockerfile: Dockerfile
    container_name: drupal
    ports:
      - "8080:80"
    environment:
      DRUPAL_DB_HOST: postgres
      DRUPAL_DB_NAME: drupal
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASS: drupal
      DRUPAL_ADMIN_USER: admin
      DRUPAL_ADMIN_PASS: admin
      DRUPAL_ADMIN_MAIL: admin@example.com
      DRUPAL_TRUSTED_HOSTS: "^localhost$,^drupal$,^127\\.0\\.0\\.1$"
      DRUPAL_SITE_NAME: "JF Startercamp - App"
    volumes:
      # Persistentes Composer-Projekt (Core + vendor + web)
      - drupal_project:/opt/drupal
      # Nur Custom-Entwicklung binden
      - ./drupal/custom/modules:/opt/drupal/web/modules/custom
      - ./drupal/custom/themes:/opt/drupal/web/themes/custom
      # Optional: Config-Verzeichnis
      # - ./drupal/config:/opt/drupal/config
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/jsonapi"]
      interval: 20s
      timeout: 5s
      retries: 15

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - postgres

  matching:
    build:
      context: ./matching
      dockerfile: Dockerfile
    container_name: matching
    environment:
      DRUPAL_URL: http://drupal/jsonapi
      # DRUPAL_TOKEN: your_token_if_applicable
    ports:
      - "5001:5000"
    volumes:
      - ./matching:/app
    depends_on:
      drupal:
        condition: service_started

  # Produktion: statisch via Nginx
  vue-prod:
    image: nginx:alpine
    container_name: vue-prod
    profiles: [prod]
    ports:
      - "3000:80"
    volumes:
      - ./vue-frontend/dist:/usr/share/nginx/html:ro
      - ./nginx/vue-site.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - drupal

volumes:
  db_data:
  drupal_project:
