services:
  drupal:
    env_file:
      - ./.env.development
    volumes:
      # Komplettes Projekt (Composer, web, vendor, scripts, config, private)
      - ./drupal:/opt/drupal
    command: ["/bin/bash", "/opt/drupal/scripts/start-drupal.sh"]

  matching:
    env_file:
      - ./.env.development

  vue:
    build:
      context: ./vue-frontend
      dockerfile: Dockerfile
      target: dev
    container_name: vue-dev
    working_dir: /app
    volumes:
      - ./vue-frontend:/app
      - vue_node_modules:/app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host 0.0.0.0
    depends_on:
      - drupal
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "-", "http://localhost:5173/"]
      interval: 10s
      timeout: 3s
      retries: 10

volumes:
  vue_node_modules:
