jfcamp_matching.settings:
  type: config_object
  label: 'JFCamp Matching settings'
  mapping:
    endpoint:
      type: string
      label: 'Matching Base URL'
    participant_bundle:
      type: string
      label: 'Bundle Teilnehmer'
    workshop_bundle:
      type: string
      label: 'Bundle Workshop'
    assignment_mode:
      type: string
      label: 'Zuweisungsmodus (auto|per_slot|multi)'
    slot_fields_prefix:
      type: string
      label: 'Slot-Feldpräfix (bei per_slot)'
    num_slots:
      type: integer
      label: 'Anzahl Slots'
    assigned_field:
      type: string
      label: 'Mehrfach-Referenzfeld (bei multi)'
