_core:
  default_config_hash: FtwnuCXmazPAh2H2i_gbDhMK1-eBmNy1dG4RBU4qt4o
langcode: de
display_denied_message: true
access_denied_message: 'Zugriff verweigert. Sie müssen sich anmelden, um diese Seite anzuzeigen.'
access_denied_message_type: error
redirect_authenticated_users_to: ''
throw_authenticated_404: false
display_auth_denied_message: true
access_denied_auth_message: 'Zugriff verweigert. Wenden Sie sich an ihren Website-Administrator, wenn Sie Hilfe benötigen.'
access_denied_auth_message_type: error
user_login_path: /user/login
default_redirect_code: 307
add_noindex_header: false
destination_parameter_override: ''
match_noredirect_pages: ''
match_noredirect_negate: 0
redirect_to_destination: true
